#!/usr/bin/env sh
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
    echo ""
    echo "======================================================="
    echo "Không được commit trực tiếp trên nhánh '$BRANCH'."
    echo "Vui lòng tạo nhánh mới bằng lệnh:"
    echo "   git checkout -b feat/ten-tinh-nang-cua-ban"
    echo "======================================================="
    echo ""
    exit 1
fi

npx lint-staged